# Generated by Django 3.0.2 on 2020-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
